# Generated by Django 4.1.5 on 2023-01-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapiApp', '0002_vendor_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='total_pur_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_sale_price',
            field=models.IntegerField(default=0),
        ),
    ]
