# Generated by Django 4.1.5 on 2023-01-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapiApp', '0003_inventory_total_pur_price_inventory_total_sale_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-date_modified'], 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='inventory',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
