# Generated by Django 4.1.5 on 2023-01-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapiApp', '0004_alter_inventory_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['date_modified'], 'verbose_name_plural': 'Inventories'},
        ),
    ]
